#!/usr/bin/env python

import logging
import json
import os
from socket import inet_aton
import sys
import time

import aaargh

from pigeon import PigeonStore


logger = logging.getLogger('pigeon')

def json_pp(s):
    return json.dumps(json.loads(s), indent=2)


def lookup_and_print(p, ip):
    value = p.lookup_ip(inet_aton(ip))
    if value is None:
        print("No hit found")
    else:
        print(json_pp(value))


app = aaargh.App(description="Fast IP geo lookup")
app.arg('--database-dir')


@app.cmd(name='load', help="Load data from a CSV file")
@app.cmd_arg('input', type=file, nargs='?', default=sys.stdin)
def load_data(input, database_dir):
    logger.debug("Loading data from %s", input)
    p = PigeonStore(database_dir)
    p.load(input)


@app.cmd(name="lookup")
@app.cmd_arg('ip', help="The IP address to lookup")
def lookup(ip, database_dir):
    p = PigeonStore(database_dir)
    lookup_and_print(p, ip)


@app.cmd(name="shell")
def shell(database_dir):
    p = PigeonStore(database_dir)
    while True:
        ip = raw_input('IP: ')
        lookup_and_print(p, ip)


@app.cmd(name='perftest', help="Run performance test")
@app.cmd_arg('--iterations', default=100 * 1000, type=int,
             help="The number of iterations")
def perftest(iterations, database_dir):
    start_time = time.time()
    p = PigeonStore(database_dir)

    rand_bytes = os.urandom
    lookup = p.lookup_ip
    for n in xrange(iterations):
        ip = rand_bytes(4)
        lookup(ip)

    elapsed = time.time() - start_time
    out = "{:d} lookups in {:.2f}s ({:.2f} req/s)".format(
        iterations, elapsed, iterations / elapsed)
    print(out)


def main():
    return app.run()


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    sys.exit(main())
